[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wf-eol-tester"
version = "0.1.0"
description = "End-of-Line (EOL) Tester for Wafer Fabrication with Clean Architecture"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.6.0",
    "asyncio-mqtt>=0.11.0",
    "pyserial>=3.5",
    "pyserial-asyncio>=0.6",
    "superclaude>=3.0.0.1",
    "numpy>=1.21.0",
    "scipy>=1.7.0",
    "pyyaml>=6.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=22.0.0",
    "isort>=5.0.0",
    "mypy>=1.0.0",
    "flake8>=4.0.0",
    "pylint>=2.15.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["src", "tests"]

[tool.flake8]
max-line-length = 100

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
