"""
AJINEXTEK DIO Controller Constants

This module contains constants specific to AJINEXTEK Digital I/O operations.
"""

# DIO Module Types
DIO_MODULE_TYPE_16IN_16OUT = 0x01
DIO_MODULE_TYPE_32IN = 0x02
DIO_MODULE_TYPE_32OUT = 0x03
DIO_MODULE_TYPE_64IN_64OUT = 0x04

# DIO Port Offsets
DIO_PORT_OFFSET_0_31 = 0
DIO_PORT_OFFSET_32_63 = 1
DIO_PORT_OFFSET_64_95 = 2
DIO_PORT_OFFSET_96_127 = 3

# DIO Operation Modes
DIO_MODE_NORMAL = 0
DIO_MODE_INTERRUPT = 1

# DIO Signal States
DIO_STATE_LOW = 0
DIO_STATE_HIGH = 1

# Default Configuration
DEFAULT_MODULE_COUNT = 4
DEFAULT_INPUT_COUNT = 32
DEFAULT_OUTPUT_COUNT = 32
MAX_MODULES_PER_SYSTEM = 32
MAX_PINS_PER_MODULE = 128

# Timing Constants (milliseconds)
DIO_READ_TIMEOUT = 100
DIO_WRITE_TIMEOUT = 100
DIO_INITIALIZATION_TIMEOUT = 5000

# Error Handling
MAX_RETRY_COUNT = 3
RETRY_DELAY_MS = 10