# Default EOL Test Configuration Profile
# This is the standard configuration used for most EOL tests

metadata:
  profile_name: "default"
  description: "Standard EOL test configuration for normal operation"
  version: "1.0"
  created_by: "System"
  created_time: "2024-01-01T00:00:00"

# Hardware configuration
hardware:
  voltage: 18.0          # Operating voltage (V)
  current: 20.0          # Current limit (A)  
  upper_temperature: 80.0 # Upper temperature limit (°C)
  fan_speed: 10          # Fan speed percentage (0-100%)
  max_stroke: 240.0      # Maximum stroke position (mm)
  initial_position: 10.0 # Initial robot position (mm)

# Test parameters
test_parameters:
  # Temperature test points (°C)
  temperature_list: [25.0, 30.0, 35.0, 40.0, 45.0, 50.0]
  
  # Stroke position test points (mm)
  stroke_positions: [10.0, 60.0, 100.0, 140.0, 180.0, 220.0, 240.0]
  
  # Standby position (mm)
  standby_position: 10.0

# Timing configuration (seconds)
timing:
  stabilization_delay: 0.5        # General stabilization wait
  temperature_stabilization: 1.0  # Temperature change stabilization
  power_stabilization: 0.5        # Power output stabilization
  loadcell_zero_delay: 0.1        # LoadCell zeroing delay

# Measurement tolerances and precision
tolerances:
  measurement_tolerance: 0.001  # General measurement tolerance
  force_precision: 2           # Force measurement decimal places
  temperature_precision: 1     # Temperature measurement decimal places

# Test execution settings
execution:
  retry_attempts: 3      # Number of retry attempts for failed operations
  timeout_seconds: 300.0 # Overall test timeout (5 minutes)

# Safety limits (absolute maximums)
safety:
  max_temperature: 100.0 # Absolute maximum temperature (°C)
  max_force: 1000.0      # Absolute maximum force (N)
  max_voltage: 30.0      # Absolute maximum voltage (V) 
  max_current: 50.0      # Absolute maximum current (A)