# High Voltage Test Configuration Profile  
# Configuration for testing with higher voltage requirements

metadata:
  profile_name: "high_voltage"
  description: "High voltage test configuration for special requirements"
  version: "1.0"
  created_by: "System"
  created_time: "2024-01-01T00:00:00"

# High voltage hardware configuration
hardware:
  voltage: 24.0          # Higher operating voltage
  current: 25.0          # Higher current limit
  upper_temperature: 85.0 # Slightly higher temperature limit
  fan_speed: 15          # Higher fan speed for cooling
  max_stroke: 240.0
  initial_position: 10.0

# Standard test parameters
test_parameters:
  temperature_list: [25.0, 30.0, 35.0, 40.0, 45.0, 50.0]
  stroke_positions: [10.0, 60.0, 100.0, 140.0, 180.0, 220.0, 240.0]
  standby_position: 10.0

# Standard timing
timing:
  stabilization_delay: 0.5
  temperature_stabilization: 1.0
  power_stabilization: 0.8        # Slightly longer for higher voltage
  loadcell_zero_delay: 0.1

# Standard tolerances
tolerances:
  measurement_tolerance: 0.001
  force_precision: 2
  temperature_precision: 1

# Standard execution
execution:
  retry_attempts: 3
  timeout_seconds: 300.0

# Adjusted safety limits for high voltage
safety:
  max_temperature: 110.0 # Higher temperature limit
  max_force: 1000.0
  max_voltage: 35.0      # Higher voltage safety limit
  max_current: 60.0      # Higher current safety limit