hardware:
  voltage: 18.0
  current: 20.0
  upper_current: 30.0
  upper_temperature: 80.0
  activation_temperature: 60.0
  standby_temperature: 40.0
  fan_speed: 10
  max_stroke: 240.0
  initial_position: 10.0
motion_control:
  velocity: 100.0
  acceleration: 100.0
  deceleration: 100.0
test_parameters:
  temperature_list:
  - 38.0
  - 40.0
  - 42.0
  - 44.0
  - 46.0
  - 48.0
  - 50.0
  - 52.0
  - 54.0
  - 56.0
  - 58.0
  - 60.0
  stroke_positions:
  - 10.0
  - 60.0
  - 100.0
  - 140.0
  - 180.0
  - 220.0
  - 240.0
timing:
  stabilization_delay: 0.1
  temperature_stabilization: 0.1
  standby_stabilization: 1.0
  power_stabilization: 0.5
  loadcell_zero_delay: 0.1
tolerances:
  measurement_tolerance: 0.001
  force_precision: 2
  temperature_precision: 1
execution:
  retry_attempts: 3
  timeout_seconds: 60.0
safety:
  max_voltage: 30.0
  max_current: 30.0
  max_velocity: 500.0
  max_acceleration: 1000.0
  max_deceleration: 1000.0
pass_criteria:
  force_limit_min: 0.0
  force_limit_max: 100.0
  temperature_limit_max: 80.0
  temperature_limit_min: -10.0
  measurement_tolerance: 0.001
  force_precision: 2
  temperature_precision: 1
  position_tolerance: 0.5
  max_test_duration: 300.0
  min_stabilization_time: 0.5
  spec_points: []
metadata:
  profile_name: default
  created_by: YamlConfiguration
  created_time: '2025-08-07T02:02:55.114753'
  version: '1.0'
