voltage: 18.0
current: 20.0
upper_temperature: 80.0
fan_speed: 10
max_stroke: 240000.0
initial_position: 10000.0
pass_criteria:
  force_limit_min: 0.0
  force_limit_max: 100.0
  temperature_limit_max: 80.0
  temperature_limit_min: -10.0
  measurement_tolerance: 0.001
  force_precision: 2
  temperature_precision: 1
  position_tolerance: 0.5
  max_test_duration: 300.0
  min_stabilization_time: 0.5
  spec_points: []
temperature_list:
- 38.0
- 40.0
- 42.0
- 44.0
- 46.0
- 48.0
- 50.0
- 52.0
- 54.0
- 56.0
- 58.0
- 60.0
stroke_positions:
- 10000.0
- 60000.0
- 100000.0
- 140000.0
- 180000.0
- 220000.0
- 240000.0
stabilization_delay: 0.1
temperature_stabilization: 0.1
power_stabilization: 0.5
loadcell_zero_delay: 0.1
measurement_tolerance: 0.001
force_precision: 2
temperature_precision: 1
retry_attempts: 3
timeout_seconds: 60.0
max_voltage: 30.0
max_current: 30.0
velocity: 60000.0
acceleration: 60000.0
deceleration: 60000.0
max_velocity: 100000.0
max_acceleration: 100000.0
max_deceleration: 100000.0
metadata:
  profile_name: default
  created_at: '2025-08-11T13:48:50.978606'
  note: Auto-generated default test profile 'default'
  created_by: YamlConfiguration (auto-generated)
